import localFont from "next/font/local";
import "./globals.css";

const vazir = localFont({
  src: [{
    path: "./fonts/Vazir.woff2",
    weight: "400",
    style: "normal"
  },
  {
    path: "./fonts/Vazir-Bold.woff2",
    weight: "800",
    style: "bold"
  },
  {
    path: "./fonts/Vazir-Light.woff2",
    weight: "300",
    style: "light"
  },
  {
    path: "./fonts/Vazir-Medium.woff2",
    weight: "500",
    style: "medium"
  },
  {
    path: "./fonts/Vazir-Thin.woff2",
    weight: "200",
    style: "thin"
  },
  ],
  variable: "--font-vazir",
})

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" dir="rtl">
      <body
        className={`${vazir.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
